apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo-create
  namespace: demo-ns
spec:
  allowStaticCreds: true
  # requestHTTPMethod: GET
  # Mount dynamic path of the secrets backend
  #mount: demo-db
  # Mount static path of the secrets backend DATABASE
  #mount: database
  # Mount static path of the secrets backend LDAP
  mount: ldap

  # Path to the secret
#  path: creds/dev-postgres
#  path: static-creds/education
  path: static-cred/test130238

  # Where to store the secrets, VSO will create the secret
  destination:
    create: true
    name: vso-db-demo-created
  renewalPercent: 1

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: vso-db-demo

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth

