apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: postgres-persistent-volume
  namespace: postgres
  # Labels for identifying PV
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: standard
  capacity:
    # PV Storage capacity
    storage: 10Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # Specify the path to persistent the volumes  
  hostPath:
    path: "/var/lib/postgresql/data"
---
apiVersion: v1
# define a resource for volume chain
kind: PersistentVolumeClaim
metadata:
  # Name the volume chain
  name: db-persistent-volume-claim
  namespace: postgres
spec:
  storageClassName: standard
  accessModes:
    # Allow ReadWrite to multiple pods
    # - ReadWriteOnce
    - ReadWriteMany
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 10Gi

